version = "1.0"

[main]
name.en = "Element configuration"
name.fr = "Configuration d'Element"

    [main.config]
    name.en = "Configuration Options"
    name.fr = "Options de configuration"

        [main.config.default_home_server]
        ask.en = "Default Home Server"
        ask.fr = "Serveur Matrix par défaut"
        type = "string"
        default = "matrix.org"
        help.en = "Define Matrix default home server address."
        help.fr = "Définir l'adresse du serveur par défaut de Matrix."

        [main.config.login_for_welcome]
        ask.en = "Display login as welcome page"
        ask.fr = "Afficher la connexion comme page d'accueil"
        type = "boolean"
        yes = true
        no = false
        help.en = "When true, the app will use the login form as a welcome page instead of the welcome page itself. This disables use of welcome_url and all welcome page functionality."
        help.fr = "Quand l'option est sélectionnée, l'application utilisera le formulaire de connexion comme page d'accueil au lieu de la page d'accueil elle-même. Cela désactive l'utilisation de welcome_url et de toutes les fonctionnalités de la page d'accueil."
