version = "1.0"

[main]
name.en = "Element configuration"
name.fr = "Configuration d'Element"

    [main.config]
    name.en = "Configuration Options"
    name.fr = "Options de configuration"

        [main.config.default_home_server]
        ask.en = "Default Home Server"
        ask.fr = "Serveur Matrix par défaut"
        type = "string"
        default = "matrix.org"
        help.en = "Define Matrix default home server address."
        help.fr = "Définir l'adresse du serveur par défaut de Matrix."

        [main.config.disable_custom_urls]
        ask.en = "Disable custom URL field on login page"
        ask.fr = "Déactiver le champ URL personnalisé sur la page login"
        type = "boolean"
        yes = 'true'
        no = 'false'

        [main.config.disable_3pid_login]
        ask.en = "Disable possibility to login with email or phone number"
        ask.fr = "Déactiver la possibilité de s'authentifier avec un email ou no de téléphone"
        type = "boolean"
        yes = 'true'
        no = 'false'

        [main.config.disable_guests]
        ask.en = "Disable guest on login page"
        ask.fr = "Déactiver le login en tant qu'invité"
        type = "boolean"
        yes = 'true'
        no = 'false'

        [main.config.default_country_code]
        ask.en = "Default country code"
        ask.fr = "Code du pay par défaut"
        type = "string"
        example = "GB"
        help.en = "By example 'FR' for France. You can refer to this page to find your favourite country code: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements"
        help.fr = "Par example 'FR' pour la France. Vous pouvez vous référer à la page suivante afin de trouver votre pays favori: https://fr.wikipedia.org/wiki/ISO_3166-1#Table_de_codage"
        pattern.regexp = "^[A-Z]{2}$"

        [main.config.brand_text]
        ask.en = "Branding text for the application"
        ask.fr = "Texte de marque pour l'application"
        type = "string"

        [main.config.default_federate]
        ask.en = "Enable fedration features by default"
        ask.fr = "Activer les fonctionnalités de fédération par défaut"
        type = "boolean"
        yes = 'true'
        no = 'false'

        [main.config.default_theme]
        ask.en = "Default theme"
        ask.fr = "Thème par défault"
        type = "select"
        choices = [ "light", "dark" ]

        [main.config.show_labs_settings]
        ask.en = "Show the experimental feature menu"
        ask.fr = "Afficher le menu des fonctions expérimentales"
        type = "boolean"
        yes = 'true'
        no = 'false'

        [main.config.sso_redirect_options]
        ask.en = "SSO redirect option"
        ask.fr = "Option de redirection SSO"
        type = "select"
        choices = ["none", "on_login_page", "on_welcome_page", "immediate"]
        default = "none"

    [main.call]
    name.en = "Audio and video call"
    name.fr = "Appels audio et video"

        [main.call.enable_element_call]
        ask.en = "Use Element Call for calls"
        ask.fr = "Utiliser Element Call pour les appels"
        type = "boolean"
        yes = 'true'
        no = 'false'

        [main.call.enable_element_call_use_exclusively]
        ask.en = "Use exclusively"
        ask.fr = "Utiliser exclusivement"
        help.en = "Specifying whether Element Call should be used exclusively as the only VoIP stack in the app, removing the ability to start legacy 1:1 calls or Jitsi calls."
        help.fr = "Spécifier si Element Call doit être utilisé exclusivement comme la seule pile VoIP dans l'application, en supprimant la possibilité de démarrer des appels 1:1 ou des appels Jitsi."
        type = "boolean"
        yes = 'true'
        no = 'false'
        visible = "enable_element_call"

        [main.call.element_call_guest_spa_url]
        ask.en = "Optional URL for an Element Call single-page"
        ask.fr = "URL facultative pour une application monopage"
        help.en = "If this is set, Element Web will expose a 'join' link for public video rooms, which can then be shared to non-matrix users. The target Element Call SPA is typically set up to use a homeserver that allows users to register without email ('passwordless guest users') and to federate. Leave it empty if you don't want to set it."
        help.fr = "Si cette option est activée, Element Web affichera un lien « joindre » pour les salles vidéo publiques, qui peuvent ensuite être partagées avec des utilisateurs ne faisant pas partie de Matrix. La cible Element Call SPA est généralement configurée pour utiliser un serveur domestique qui permet aux utilisateurs de s'inscrire sans e-mail (« utilisateurs invités sans mot de passe ») et de se fédérer. Laissez ce champ vide si vous ne souhaitez pas le paramétrer."
        type = "string"
        default = ""
        example = "https://call.element.io"
        visible = "enable_element_call"
