packaging_format = 2

id = "element"
name = "Element"
description.en = "Web client for Matrix"
description.fr = "Client web pour Matrix"

version = "1.11.13~ynh1"

maintainers = ["Josué Tille"]

[upstream]
license = "Apache-2.0"
website = "https://element.io"
demo = "https://app.element.io/"
admindoc = "https://element.io/help"
code = "https://github.com/vector-im/element-web/"
cpe = "cpe:2.3:a:matrix:element"

[integration]
yunohost = ">= 11.1.0"
architectures = "all"
multi_instance = true
ldap = false
sso = true
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/element"

    [install.default_home_server]
    ask.en = "Choose a default home server"
    ask.fr = "Choisissez un serveur par défault"
    type = "string"
    example = "my-own-homeserver.tld"
    default = "matrix.org"

    [install.init_main_permission]
    help.en = "A public application means that anyone can access it. Note that this application provides just files (html, javascript, images, etc.)"
    help.fr = "Une application publique signifie que n'importe qui peut y accéder. Notez que cette application ne fournit que des fichiers (html, javascript, images, etc.)"
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
