packaging_format = 2

id = "element"
name = "Element"
description.en = "Web client for Matrix"
description.fr = "Client web pour Matrix"

version = "1.11.89~ynh1"

maintainers = ["Josué Tille"]

[upstream]
license = "Apache-2.0"
website = "https://element.io"
demo = "https://app.element.io/"
admindoc = "https://element.io/help"
code = "https://github.com/element-hq/element-web"
cpe = "cpe:2.3:a:matrix:element"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "70M"
ram.build = "0M"
ram.runtime = "0M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/element"

    [install.default_home_server]
    ask.en = "Choose a default Matrix server"
    ask.fr = "Choisissez un serveur Matrix par défault"
    type = "string"
    example = "my-own-homeserver.tld"
    default = "matrix.org"

    [install.init_main_permission]
    help.en = "'visitors' permission means that anyone can access the Element application."
    help.fr = "Autoriser les 'Visiteurs' signifie que n'importe qui peut accéder l'application Element."
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/element-hq/element-web/releases/download/v1.11.89/element-v1.11.89.tar.gz"
        sha256 = "b13a4bc015636b1222f46fc9dc10d8510d52e4b622215ea5b0883d6e662dde5f"
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "^element-v.*.tar.gz$"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    # Need to allow access freely to /bundles because for somes request the authentication (from ssowat) are not send
    # By example the usercontent.js file is not requested with any cookie header when we try to download an attachment
    # And so without this the request will be redirected on the SSO portail which break attachment download
    bundles.url = "/bundles"
    bundles.label = "Bundles resources"
    bundles.allowed = "visitors"
    bundles.auth_header = false
    bundles.show_tile = false
    bundles.protected = true
