test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude ="install.nourl"

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    default_home_server="matrix.org"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.d653976.name = "Upgrade from 23.01"
