#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

disable_custom_urls=false
disable_guests=false
disable_3pid_login=false
default_country_code=GB
brand_text=Element
default_federate=true
default_theme=light
show_labs_settings=false

ynh_app_setting_set --key=disable_custom_urls --value=$disable_custom_urls
ynh_app_setting_set --key=disable_guests --value=$disable_guests
ynh_app_setting_set --key=disable_3pid_login --value=$disable_3pid_login
ynh_app_setting_set --key=default_country_code --value=$default_country_code
ynh_app_setting_set --key=brand_text --value=$brand_text
ynh_app_setting_set --key=default_federate --value=$default_federate
ynh_app_setting_set --key=default_theme --value=$default_theme
ynh_app_setting_set --key=show_labs_settings --value=$show_labs_settings

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

configure_element

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
