#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression 'Ensuring downward compatibility...'

if [ -z "${default_home_server:-}" ]; then
    default_home_server='matrix.org'
    ynh_app_setting_set --key=default_home_server --value=$default_home_server
fi

if [ -z "${disable_custom_urls:-}" ]; then
    disable_custom_urls=false
    ynh_app_setting_set --key=disable_custom_urls --value=$disable_custom_urls
fi

if [ -z "${disable_guests:-}" ]; then
    disable_guests=false
    ynh_app_setting_set --key=disable_guests --value=$disable_guests
fi

if [ -z "${disable_3pid_login:-}" ]; then
    disable_3pid_login=false
    ynh_app_setting_set --key=disable_3pid_login --value=$disable_3pid_login
fi

if [ -z "${default_country_code:-}" ]; then
    default_country_code=false
    ynh_app_setting_set --key=default_country_code --value=$default_country_code
fi

if [ -z "${brand_text:-}" ]; then
    brand_text=Element
    ynh_app_setting_set --key=brand_text --value=$brand_text
fi

if [ -z "${default_federate:-}" ]; then
    default_federate=true
    ynh_app_setting_set --key=default_federate --value=$default_federate
fi

if [ -z "${default_theme:-}" ]; then
    default_theme=light
    ynh_app_setting_set --key=default_theme --value=$default_theme
fi

if [ -z "${show_labs_settings:-}" ]; then
    show_labs_settings=false
    ynh_app_setting_set --key=show_labs_settings --value=$show_labs_settings
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config.json"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

configure_element

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
