#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression 'Ensuring downward compatibility...'

ynh_app_setting_set_default --key=default_home_server --value='matrix.org'
set_settings_default

# Enable only one time the parameter enable_element_call because most of user will at some point migrate to element call
# and we want to avoid that many users just don't understand how to use element call
# (because they don't know the existence of this settings in the config panel)
if ynh_app_upgrading_from_version_before_or_equal_to '1.11.102~ynh1'; then
    ynh_app_setting_set --key=enable_element_call --value=true
    enable_element_call=true
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config.json"

chmod -R o-rwx "$install_dir"
chown -R "$app":www-data "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

configure_element

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
